os: linux
language: c
install: bash <(curl -s https://raw.githubusercontent.com/Nycto/ExtraNimble/master/travis-setup.sh)
before_script: export PATH="nim/bin:$PATH"
script: nimble all
sudo: false
cache:
  directories:
    - $HOME/Nim
